### ISSUE TITLE
Best way to remove li.divider in 

### ISSUE THREAD

**Issue by frankstallone** [milohuang/reverie#209]
Line 136 in foundation.php I changed from:

``` PHP
$output .= $indent . ( $this->nav_bar['in_top_bar'] == true ? '<li class="divider"></li>' : '' ) . '<' . $this->nav_bar['item_type'] . ' id="menu-item-'. $item->ID . '"' . $value . $class_names .'>';
```

to:

``` PHP
$output .= $indent . ( $this->nav_bar['in_top_bar'] == true ? '' : '' ) . '<' . $this->nav_bar['item_type'] . ' id="menu-item-'. $item->ID . '"' . $value . $class_names .'>';
```

but I am no PHP guru, is there a better way to stop having the dividers between navigation items? With my little knowledge I read that PHP as if the nav_bar is in_top_bar than execute adding li.divider between items, else nothing. Technically I don't want the divider so as I am writing this I just made the line:

``` PHP
$output .= $indent . '<' . $this->nav_bar['item_type'] . ' id="menu-item-'. $item->ID . '"' . $value . $class_names .'>';
```

effectively removing that entire evaluation and it still seem to work. Does the above line break anything else I don't know about?

Thank you for your time and patience,
Frank

**Comment by Mudh** [comment]
Hi, I had the same issue and resolve it with jQuery:

jQuery(function($){
       $(".divider").remove();
});

It's quite simple but It works and you don't have to touch anything in the function.php file. More secure way...
See ya !
